#!/bin/bash
set -v
echo "Lancement du jeu ..."
pkill rmiregistry
rmiregistry 5000 &
rmiregistry 5001 &
rmiregistry 5002 &
sleep 2
echo "Lancement du coordinateur ..."
xterm -e "java Mainexemple; $SHELL" &
sleep 2
echo "Lancement du producteur ..."
xterm -e "java ProducteurImpl localhost 5000 localhost 5001; $SHELL" &
sleep 2
echo "Lancement du joueur ..."
xterm -e "java JoueurImpl localhost 5000 localhost 5002; $SHELL" &
