enum TYPE { ARGENT, OR, BOIS };

enum COMPORTEMENT {COOPERATIF,VOLEUR,TRAITRE,INDIVIDUALISTE,ATTENTIONNEL,BRUTE,HUMAIN};

enum ETAT {OBSERVE,PREND_RESSOURCES,VOLE,ATTEND,PENALITE,PENALITE2,PENALITE3};
